#ifndef CONSTRUCT_CAL_GLOBAL_H
#define CONSTRUCT_CAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONSTRUCT_CAL_LIBRARY)
#  define CONSTRUCT_CAL_EXPORT Q_DECL_EXPORT
#else
#  define CONSTRUCT_CAL_EXPORT Q_DECL_IMPORT
#endif

#endif // CONSTRUCT_CAL_GLOBAL_H
